### ISSUE TITLE
Cannot read property 'InsertAsSnippet' of undefined

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/monaco-promql#1]
Issue tranfered from the initial repository: https://github.com/celian-garcia/monaco-languages-promql/issues/7

> When I tried to implement promql language in my angular project I have faced below error
Cannot read property 'InsertAsSnippet' of undefined

@suhaskurade8

**Comment by celian-garcia** [comment]
Hi @suhaskurade8, if you want a java support  I suggest you to look at this repository. https://github.com/microsoft/monaco-languages
This the official languages support of monaco editor but I think it contains only the syntax highlighting.


If you want to have more features for Java like autocompletion for example, you will have to create your own repository like we did for promql basically.

For further readings here is the question I posted few months ago to monaco editor about the integration of such a repository https://github.com/microsoft/monaco-editor/issues/1672

Hope I answered your question.
Cheers and Happy Easter !

**Comment by celian-garcia** [comment]
Oh and by the way for the integration of monaco-editor in angular, everything is here https://github.com/atularen/ngx-monaco-editor

**Comment by suhaskurade8** [comment]
Hi @celian-garcia 
Thank you so much for your reply.
Currently, I'm using ngx-monaco-editor in my angular project. I thought there is a custom repository available for the java like promql repository. Here I understand that, if I need autocompletion for java language, I need to create my own repository. I have tried https://github.com/microsoft/monaco-languages, but unfortunately, it only supports syntax highlighting.
Please let me know if you know any repository for the below languages : 
C,C++,C#, Java, Python & PHP

Again thanks a lot for your valuable time and reply.
Happy Easter !

**Comment by Nexucis** [comment]
So basically there is no issue with the promQL language in monaco :).
I think for the others questions you had, you will have to search by yourself. And if nobody already provides an auto-completion for the language you mentioned, then maybe you will be the first to provide it :)

I'm closing the issue since, there is no problem relative to monao-promql .
