### ISSUE TITLE
Paths in package.json don't exist

### ISSUE THREAD

**Issue by arendjr** [prometheus-community/monaco-promql#20]
The project's `package.json` refers to `lib/index.js` and `lib/index.d.ts`, but these files don't exist in the package as published to NPM. It seems this is not a problem for Webpack and TypeScript, which will fall back to the default `index.js` and `index.d.ts` in the root of the project, where they do exist. However, other tools such as Snowpack, which appear to be more strict with this do struggle because of this.

**Comment by celian-garcia** [comment]
Hello @arendjr, thanks for the contribution. I'm having a look

**Comment by celian-garcia** [comment]
Ah yes ! you are right we publish the content of lib folder 😄 sorry for that I accept the PR, and I will release a 1.6.1 today.

**Comment by celian-garcia** [comment]
1.6.1 released successfully, it should be available soon https://www.npmjs.com/package/monaco-promql

**Comment by arendjr** [comment]
Thanks! 👍
