### ISSUE TITLE
Rights issue on this repository

### ISSUE THREAD

**Issue by celian-garcia** [prometheus-community/monaco-promql#3]
Hello guys ! 
Thanks for the move to prometheus-community !
As the main committer of this repository I was expecting to have some priviligied rights on this repository, but I can't even accept a PR :/ 
Is that normal ??
Cheers

**Comment by Nexucis** [comment]
mmm no I think I forget it

**Comment by Nexucis** [comment]
Actually I can't do that, you have to be part of the prometheus-community first.
@juliusv is it something possible to invite @celian-garcia in the prometheus-community ? 

It seems I don't have the right to add people to the team. Maybe it's normal @juliusv ? In that case if it's ok to invite him to the prometheus-community then can you add him to the team too ?

**Comment by juliusv** [comment]
Sure, I invited @celian-garcia to the `prometheus-community/editor-plugins` team. Anyone else who should have access?

**Comment by Nexucis** [comment]
thanks @juliusv :). No we are fine now!

**Comment by celian-garcia** [comment]
Ok thanks @juliusv ! I received it and joined successfully ;)

**Comment by juliusv** [comment]
Great :)
