### ISSUE TITLE
Typescript type definitions missing in 1.7.0

### ISSUE THREAD

**Issue by LukeTillman** [prometheus-community/monaco-promql#32]
We just went to upgrade to the latest version (1.7.0) and noticed that the type definitions were missing from the package. Looks like maybe this change here caused it:

https://github.com/prometheus-community/monaco-promql/commit/71e5ff4bb51263f24a4d3dd4b0b475ce5a64ff96#diff-95914b3c221e1dbba96119f8305771d272ba5b18e9ea2549ad32dfd931cf0289L6

I suspect it's likely just a matter of adding back that `declaration: true` config flag to fix it, although I don't have all the context on why you may have removed it.

**Comment by celian-garcia** [comment]
Hello, yeah I tried to be closer to the original monaco-languages repo
https://github.com/microsoft/monaco-languages/blob/main/src/tsconfig.esm.json

I guess I can have it back. I'll release a 1.7.1 with that :)

**Comment by celian-garcia** [comment]
v1.7.1 released 
https://www.npmjs.com/package/monaco-promql/v/1.7.1
https://github.com/prometheus-community/monaco-promql/releases/tag/v1.7.1

**Comment by LukeTillman** [comment]
Thank you!
